server:
  port: 7000
  error:
    include-message: always

logging:
  level:
    root: WARN
    dev.michaeldubose: DEBUG

app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003